const fs = require("fs");
const path = require("path");

const uploadsDir = path.join(__dirname, "../uploads");

const sanitize = (value) =>
  String(value ?? "")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "")
    .replace(/\s+/g, " ")
    .trim();

const pdfText = (value) =>
  sanitize(value)
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");

const wrapText = (text, maxChars = 82) => {
  const words = sanitize(text).split(" ").filter(Boolean);
  const lines = [];
  let line = "";

  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > maxChars && line) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
};

const buildContentStream = (order) => {
  const patient = order.patientId || {};
  const doctor = order.doctorId || {};
  const hospitalName = sanitize(doctor.hospital || process.env.HOSPITAL_NAME || "ChatAid Clinic");
  const reportDate = new Date(order.completedAt || Date.now()).toLocaleString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const lines = [];
  const add = (text, size = 10, x = 54, gap = 16) => lines.push({ text, size, x, gap });
  const section = (text) => {
    lines.push({ rule: true, gap: 10 });
    add(text, 13, 54, 18);
  };

  lines.push({ logo: true });
  add(hospitalName, 18, 110, 22);
  add("Laboratory Result Report", 12, 110, 18);
  add(`Report date: ${reportDate}`, 9, 110, 22);

  section("Patient Details");
  add(`Name: ${patient.name || "Patient"}`);
  add(`Email/Phone: ${patient.email || patient.phone || "Not provided"}`);
  add(`Age/Gender: ${patient.age || "Not provided"} / ${patient.gender || "Not provided"}`);

  section("Ordering Doctor");
  add(`Doctor: Dr. ${doctor.name || "Doctor"}`);
  add(`Department: ${order.department || doctor.specialisation || doctor.specialization || "General"}`);

  section("Tests Ordered");
  wrapText((order.tests || []).join(", "), 78).forEach((line) => add(line));

  section("Results");
  if (!order.results?.length) {
    add("No structured result values were entered.");
  } else {
    order.results.forEach((result, index) => {
      add(`${index + 1}. ${result.testName}`, 11, 54, 15);
      add(`   Value: ${result.value || result.values || "Not entered"} ${result.unit || ""}`);
      add(`   Normal Range: ${result.normalRange || "Not specified"}`);
      add(`   Flag: ${result.flag || "None"}`);
      if (result.values && result.value) {
        wrapText(`   Notes: ${result.values}`, 78).forEach((line) => add(line));
      }
      lines.push({ gapOnly: true, gap: 5 });
    });
  }

  if (order.notes) {
    section("Doctor Notes");
    wrapText(order.notes, 78).forEach((line) => add(line));
  }

  lines.push({ rule: true, gap: 18 });
  add("Generated by ChatAid Clinic Lab System", 9, 54, 12);

  const pages = [];
  let current = [];
  let y = 770;

  const pushPage = () => {
    pages.push(current);
    current = [];
    y = 770;
  };

  for (const line of lines) {
    const gap = line.gap || 16;
    if (y - gap < 48) pushPage();
    current.push({ ...line, y });
    y -= gap;
  }
  if (current.length) pages.push(current);

  return pages.map((page, pageIndex) => {
    const chunks = [
      "q",
      "0.035 0.565 0.675 rg",
      "54 724 42 42 re f",
      "Q",
      "BT /F2 22 Tf 67 738 Td (H) Tj ET",
    ];

    page.forEach((line) => {
      if (line.logo) return;
      if (line.rule) {
        chunks.push("q 0.75 0.80 0.88 RG 54 " + line.y + " m 558 " + line.y + " l S Q");
        return;
      }
      if (line.gapOnly) return;
      chunks.push(`BT /${line.size >= 13 ? "F2" : "F1"} ${line.size} Tf ${line.x} ${line.y} Td (${pdfText(line.text)}) Tj ET`);
    });

    chunks.push(`BT /F1 8 Tf 520 28 Td (Page ${pageIndex + 1} of ${pages.length}) Tj ET`);
    return chunks.join("\n");
  });
};

const createPdfBuffer = (streams) => {
  const objects = [];
  const addObject = (body) => {
    objects.push(body);
    return objects.length;
  };

  const catalogId = addObject("<< /Type /Catalog /Pages 2 0 R >>");
  const pagesId = addObject("");
  const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const boldFontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
  const pageIds = [];

  streams.forEach((stream) => {
    const contentId = addObject(`<< /Length ${Buffer.byteLength(stream, "binary")} >>\nstream\n${stream}\nendstream`);
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R /F2 ${boldFontId} 0 R >> >> /Contents ${contentId} 0 R >>`);
    pageIds.push(pageId);
  });

  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, "binary"));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefStart = Buffer.byteLength(pdf, "binary");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return Buffer.from(pdf, "binary");
};

const generateLabReportPdf = async (order) => {
  await fs.promises.mkdir(uploadsDir, { recursive: true });
  const streams = buildContentStream(order);
  const buffer = createPdfBuffer(streams);
  const filename = `lab-report-${order._id}-${Date.now()}.pdf`;
  const filePath = path.join(uploadsDir, filename);
  await fs.promises.writeFile(filePath, buffer);
  return { filename, filePath };
};

module.exports = { generateLabReportPdf };
